# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

modmenu_version=18.0.1
midnightlib_version=1.9.3+26.1-fabric

mod_version=1.1.0
maven_group=qouteall.dimlib
archives_base_name=dimlib

# don't forget to update this if branch changes
git_branch=1.21.3

minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.155.3+26.1.2