# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

modmenu_version=12.0.0-beta.1
midnightlib_version=1.6.4-fabric

mod_version=1.1.0
maven_group=qouteall.dimlib
archives_base_name=dimlib

# don't forget to update this if branch changes
git_branch=1.21.3

minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.9

# Fabric API
fabric_version=0.110.0+1.21.3